query queryLibrary($userId: Int!, $sort: [MediaListSort!]!, $perChunk: Int!, $chunk: Int!, $status: MediaListStatus!) {
  MediaListCollection(userId: $userId, sort: $sort, perChunk: $perChunk, chunk: $chunk, type: ANIME, forceSingleCompletedList: true, status: $status) {
    lists {
      entries {
        id
        progress
        status
        media {
          id
          idMal
          title {
            english
            romaji
            native
          }
          episodes
        }
      }
    }
    hasNextChunk
  }
}

query queryWorks($workIds: [Int!]!) {
  MediaList(mediaId_in: $workIds) {
    status
    progress
    media {
      id
      idMal
      title {
        english
        romaji
        native
      }
      episodes
    }
  }
}
