query queryLibrary($states: [StatusState!], $after: String, $amount: Int) {
  viewer {
    libraryEntries(states: $states, after: $after, first: $amount) {
      nodes {
        work {
          id
          annictId
          malAnimeId
          titleEn
          titleRo
          title
          noEpisodes
          episodes {
            nodes {
              viewerDidTrack
            }
          }
          viewerStatusState
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        endCursor
      }
    }
  }
}

query queryWorks($workIds: [Int!]) {
  searchWorks(annictIds: $workIds) {
    nodes {
      id
      annictId
      malAnimeId
      titleEn
      titleRo
      title
      noEpisodes
      episodes {
        nodes {
          viewerDidTrack
        }
      }
      viewerStatusState
    }
  }
}
